---
- hosts: '{{ host }}'
  become: yes

  vars:
    container_image: rabbitmq:3-management
    port: 15672:15672

  tasks:
  - name: PULL IMAGE
    docker_image: name={{ container_image }} source=pull

  - name: CRAETE CONTAINER
    docker_container:
      hostname: my-rabbit 
      name: some-rabbit
      image: "{{ container_image }}"
      ports:
        - "{{ port }}"
      state: present
 
  - name: CHECK STATUS CONTAINER
    docker_container_info:
      name: some-rabbit
    register: result

  - name: PRINT STATUS
    debug: var=result.container.State.Running
    when: result.exists

  - name: RESTART CONTAINER
    docker_container: name=some-rabbit state=started restart=yes
    remote_user: psapp
    when: result.exists and result.container.State.Running == false

  
    
